# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jacob/Programming/shooter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jacob/Programming/shooter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacob/Programming/shooter/CMakeFiles /home/jacob/Programming/shooter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacob/Programming/shooter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

src/Bullet.o: src/Bullet.cpp.o

.PHONY : src/Bullet.o

# target to build an object file
src/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Bullet.cpp.o
.PHONY : src/Bullet.cpp.o

src/Bullet.i: src/Bullet.cpp.i

.PHONY : src/Bullet.i

# target to preprocess a source file
src/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Bullet.cpp.i
.PHONY : src/Bullet.cpp.i

src/Bullet.s: src/Bullet.cpp.s

.PHONY : src/Bullet.s

# target to generate assembly for a file
src/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Bullet.cpp.s
.PHONY : src/Bullet.cpp.s

src/CubicCurve.o: src/CubicCurve.cpp.o

.PHONY : src/CubicCurve.o

# target to build an object file
src/CubicCurve.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/CubicCurve.cpp.o
.PHONY : src/CubicCurve.cpp.o

src/CubicCurve.i: src/CubicCurve.cpp.i

.PHONY : src/CubicCurve.i

# target to preprocess a source file
src/CubicCurve.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/CubicCurve.cpp.i
.PHONY : src/CubicCurve.cpp.i

src/CubicCurve.s: src/CubicCurve.cpp.s

.PHONY : src/CubicCurve.s

# target to generate assembly for a file
src/CubicCurve.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/CubicCurve.cpp.s
.PHONY : src/CubicCurve.cpp.s

src/Enemy.o: src/Enemy.cpp.o

.PHONY : src/Enemy.o

# target to build an object file
src/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Enemy.cpp.o
.PHONY : src/Enemy.cpp.o

src/Enemy.i: src/Enemy.cpp.i

.PHONY : src/Enemy.i

# target to preprocess a source file
src/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Enemy.cpp.i
.PHONY : src/Enemy.cpp.i

src/Enemy.s: src/Enemy.cpp.s

.PHONY : src/Enemy.s

# target to generate assembly for a file
src/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Enemy.cpp.s
.PHONY : src/Enemy.cpp.s

src/EnemyBuilder.o: src/EnemyBuilder.cpp.o

.PHONY : src/EnemyBuilder.o

# target to build an object file
src/EnemyBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/EnemyBuilder.cpp.o
.PHONY : src/EnemyBuilder.cpp.o

src/EnemyBuilder.i: src/EnemyBuilder.cpp.i

.PHONY : src/EnemyBuilder.i

# target to preprocess a source file
src/EnemyBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/EnemyBuilder.cpp.i
.PHONY : src/EnemyBuilder.cpp.i

src/EnemyBuilder.s: src/EnemyBuilder.cpp.s

.PHONY : src/EnemyBuilder.s

# target to generate assembly for a file
src/EnemyBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/EnemyBuilder.cpp.s
.PHONY : src/EnemyBuilder.cpp.s

src/EnemyFactory.o: src/EnemyFactory.cpp.o

.PHONY : src/EnemyFactory.o

# target to build an object file
src/EnemyFactory.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/EnemyFactory.cpp.o
.PHONY : src/EnemyFactory.cpp.o

src/EnemyFactory.i: src/EnemyFactory.cpp.i

.PHONY : src/EnemyFactory.i

# target to preprocess a source file
src/EnemyFactory.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/EnemyFactory.cpp.i
.PHONY : src/EnemyFactory.cpp.i

src/EnemyFactory.s: src/EnemyFactory.cpp.s

.PHONY : src/EnemyFactory.s

# target to generate assembly for a file
src/EnemyFactory.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/EnemyFactory.cpp.s
.PHONY : src/EnemyFactory.cpp.s

src/GameObject.o: src/GameObject.cpp.o

.PHONY : src/GameObject.o

# target to build an object file
src/GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameObject.cpp.o
.PHONY : src/GameObject.cpp.o

src/GameObject.i: src/GameObject.cpp.i

.PHONY : src/GameObject.i

# target to preprocess a source file
src/GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameObject.cpp.i
.PHONY : src/GameObject.cpp.i

src/GameObject.s: src/GameObject.cpp.s

.PHONY : src/GameObject.s

# target to generate assembly for a file
src/GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameObject.cpp.s
.PHONY : src/GameObject.cpp.s

src/GameOverState.o: src/GameOverState.cpp.o

.PHONY : src/GameOverState.o

# target to build an object file
src/GameOverState.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameOverState.cpp.o
.PHONY : src/GameOverState.cpp.o

src/GameOverState.i: src/GameOverState.cpp.i

.PHONY : src/GameOverState.i

# target to preprocess a source file
src/GameOverState.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameOverState.cpp.i
.PHONY : src/GameOverState.cpp.i

src/GameOverState.s: src/GameOverState.cpp.s

.PHONY : src/GameOverState.s

# target to generate assembly for a file
src/GameOverState.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameOverState.cpp.s
.PHONY : src/GameOverState.cpp.s

src/GameState.o: src/GameState.cpp.o

.PHONY : src/GameState.o

# target to build an object file
src/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameState.cpp.o
.PHONY : src/GameState.cpp.o

src/GameState.i: src/GameState.cpp.i

.PHONY : src/GameState.i

# target to preprocess a source file
src/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameState.cpp.i
.PHONY : src/GameState.cpp.i

src/GameState.s: src/GameState.cpp.s

.PHONY : src/GameState.s

# target to generate assembly for a file
src/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/GameState.cpp.s
.PHONY : src/GameState.cpp.s

src/LevelDisplay.o: src/LevelDisplay.cpp.o

.PHONY : src/LevelDisplay.o

# target to build an object file
src/LevelDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/LevelDisplay.cpp.o
.PHONY : src/LevelDisplay.cpp.o

src/LevelDisplay.i: src/LevelDisplay.cpp.i

.PHONY : src/LevelDisplay.i

# target to preprocess a source file
src/LevelDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/LevelDisplay.cpp.i
.PHONY : src/LevelDisplay.cpp.i

src/LevelDisplay.s: src/LevelDisplay.cpp.s

.PHONY : src/LevelDisplay.s

# target to generate assembly for a file
src/LevelDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/LevelDisplay.cpp.s
.PHONY : src/LevelDisplay.cpp.s

src/LinearCurve.o: src/LinearCurve.cpp.o

.PHONY : src/LinearCurve.o

# target to build an object file
src/LinearCurve.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/LinearCurve.cpp.o
.PHONY : src/LinearCurve.cpp.o

src/LinearCurve.i: src/LinearCurve.cpp.i

.PHONY : src/LinearCurve.i

# target to preprocess a source file
src/LinearCurve.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/LinearCurve.cpp.i
.PHONY : src/LinearCurve.cpp.i

src/LinearCurve.s: src/LinearCurve.cpp.s

.PHONY : src/LinearCurve.s

# target to generate assembly for a file
src/LinearCurve.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/LinearCurve.cpp.s
.PHONY : src/LinearCurve.cpp.s

src/MenuState.o: src/MenuState.cpp.o

.PHONY : src/MenuState.o

# target to build an object file
src/MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/MenuState.cpp.o
.PHONY : src/MenuState.cpp.o

src/MenuState.i: src/MenuState.cpp.i

.PHONY : src/MenuState.i

# target to preprocess a source file
src/MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/MenuState.cpp.i
.PHONY : src/MenuState.cpp.i

src/MenuState.s: src/MenuState.cpp.s

.PHONY : src/MenuState.s

# target to generate assembly for a file
src/MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/MenuState.cpp.s
.PHONY : src/MenuState.cpp.s

src/Path.o: src/Path.cpp.o

.PHONY : src/Path.o

# target to build an object file
src/Path.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Path.cpp.o
.PHONY : src/Path.cpp.o

src/Path.i: src/Path.cpp.i

.PHONY : src/Path.i

# target to preprocess a source file
src/Path.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Path.cpp.i
.PHONY : src/Path.cpp.i

src/Path.s: src/Path.cpp.s

.PHONY : src/Path.s

# target to generate assembly for a file
src/Path.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Path.cpp.s
.PHONY : src/Path.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/SlowGun.o: src/SlowGun.cpp.o

.PHONY : src/SlowGun.o

# target to build an object file
src/SlowGun.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/SlowGun.cpp.o
.PHONY : src/SlowGun.cpp.o

src/SlowGun.i: src/SlowGun.cpp.i

.PHONY : src/SlowGun.i

# target to preprocess a source file
src/SlowGun.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/SlowGun.cpp.i
.PHONY : src/SlowGun.cpp.i

src/SlowGun.s: src/SlowGun.cpp.s

.PHONY : src/SlowGun.s

# target to generate assembly for a file
src/SlowGun.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/SlowGun.cpp.s
.PHONY : src/SlowGun.cpp.s

src/SpawnElement.o: src/SpawnElement.cpp.o

.PHONY : src/SpawnElement.o

# target to build an object file
src/SpawnElement.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/SpawnElement.cpp.o
.PHONY : src/SpawnElement.cpp.o

src/SpawnElement.i: src/SpawnElement.cpp.i

.PHONY : src/SpawnElement.i

# target to preprocess a source file
src/SpawnElement.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/SpawnElement.cpp.i
.PHONY : src/SpawnElement.cpp.i

src/SpawnElement.s: src/SpawnElement.cpp.s

.PHONY : src/SpawnElement.s

# target to generate assembly for a file
src/SpawnElement.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/SpawnElement.cpp.s
.PHONY : src/SpawnElement.cpp.s

src/Spawner.o: src/Spawner.cpp.o

.PHONY : src/Spawner.o

# target to build an object file
src/Spawner.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Spawner.cpp.o
.PHONY : src/Spawner.cpp.o

src/Spawner.i: src/Spawner.cpp.i

.PHONY : src/Spawner.i

# target to preprocess a source file
src/Spawner.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Spawner.cpp.i
.PHONY : src/Spawner.cpp.i

src/Spawner.s: src/Spawner.cpp.s

.PHONY : src/Spawner.s

# target to generate assembly for a file
src/Spawner.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Spawner.cpp.s
.PHONY : src/Spawner.cpp.s

src/StandardGun.o: src/StandardGun.cpp.o

.PHONY : src/StandardGun.o

# target to build an object file
src/StandardGun.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/StandardGun.cpp.o
.PHONY : src/StandardGun.cpp.o

src/StandardGun.i: src/StandardGun.cpp.i

.PHONY : src/StandardGun.i

# target to preprocess a source file
src/StandardGun.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/StandardGun.cpp.i
.PHONY : src/StandardGun.cpp.i

src/StandardGun.s: src/StandardGun.cpp.s

.PHONY : src/StandardGun.s

# target to generate assembly for a file
src/StandardGun.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/StandardGun.cpp.s
.PHONY : src/StandardGun.cpp.s

src/State.o: src/State.cpp.o

.PHONY : src/State.o

# target to build an object file
src/State.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/State.cpp.o
.PHONY : src/State.cpp.o

src/State.i: src/State.cpp.i

.PHONY : src/State.i

# target to preprocess a source file
src/State.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/State.cpp.i
.PHONY : src/State.cpp.i

src/State.s: src/State.cpp.s

.PHONY : src/State.s

# target to generate assembly for a file
src/State.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/State.cpp.s
.PHONY : src/State.cpp.s

src/StateManager.o: src/StateManager.cpp.o

.PHONY : src/StateManager.o

# target to build an object file
src/StateManager.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/StateManager.cpp.o
.PHONY : src/StateManager.cpp.o

src/StateManager.i: src/StateManager.cpp.i

.PHONY : src/StateManager.i

# target to preprocess a source file
src/StateManager.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/StateManager.cpp.i
.PHONY : src/StateManager.cpp.i

src/StateManager.s: src/StateManager.cpp.s

.PHONY : src/StateManager.s

# target to generate assembly for a file
src/StateManager.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/StateManager.cpp.s
.PHONY : src/StateManager.cpp.s

src/TextureManager.o: src/TextureManager.cpp.o

.PHONY : src/TextureManager.o

# target to build an object file
src/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TextureManager.cpp.o
.PHONY : src/TextureManager.cpp.o

src/TextureManager.i: src/TextureManager.cpp.i

.PHONY : src/TextureManager.i

# target to preprocess a source file
src/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TextureManager.cpp.i
.PHONY : src/TextureManager.cpp.i

src/TextureManager.s: src/TextureManager.cpp.s

.PHONY : src/TextureManager.s

# target to generate assembly for a file
src/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TextureManager.cpp.s
.PHONY : src/TextureManager.cpp.s

src/TriGun.o: src/TriGun.cpp.o

.PHONY : src/TriGun.o

# target to build an object file
src/TriGun.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TriGun.cpp.o
.PHONY : src/TriGun.cpp.o

src/TriGun.i: src/TriGun.cpp.i

.PHONY : src/TriGun.i

# target to preprocess a source file
src/TriGun.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TriGun.cpp.i
.PHONY : src/TriGun.cpp.i

src/TriGun.s: src/TriGun.cpp.s

.PHONY : src/TriGun.s

# target to generate assembly for a file
src/TriGun.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TriGun.cpp.s
.PHONY : src/TriGun.cpp.s

src/TriGunUpgrade.o: src/TriGunUpgrade.cpp.o

.PHONY : src/TriGunUpgrade.o

# target to build an object file
src/TriGunUpgrade.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TriGunUpgrade.cpp.o
.PHONY : src/TriGunUpgrade.cpp.o

src/TriGunUpgrade.i: src/TriGunUpgrade.cpp.i

.PHONY : src/TriGunUpgrade.i

# target to preprocess a source file
src/TriGunUpgrade.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TriGunUpgrade.cpp.i
.PHONY : src/TriGunUpgrade.cpp.i

src/TriGunUpgrade.s: src/TriGunUpgrade.cpp.s

.PHONY : src/TriGunUpgrade.s

# target to generate assembly for a file
src/TriGunUpgrade.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/TriGunUpgrade.cpp.s
.PHONY : src/TriGunUpgrade.cpp.s

src/Upgrade.o: src/Upgrade.cpp.o

.PHONY : src/Upgrade.o

# target to build an object file
src/Upgrade.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Upgrade.cpp.o
.PHONY : src/Upgrade.cpp.o

src/Upgrade.i: src/Upgrade.cpp.i

.PHONY : src/Upgrade.i

# target to preprocess a source file
src/Upgrade.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Upgrade.cpp.i
.PHONY : src/Upgrade.cpp.i

src/Upgrade.s: src/Upgrade.cpp.s

.PHONY : src/Upgrade.s

# target to generate assembly for a file
src/Upgrade.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/Upgrade.cpp.s
.PHONY : src/Upgrade.cpp.s

src/World.o: src/World.cpp.o

.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i

.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s

.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/index.o: src/index.cpp.o

.PHONY : src/index.o

# target to build an object file
src/index.cpp.o:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/index.cpp.o
.PHONY : src/index.cpp.o

src/index.i: src/index.cpp.i

.PHONY : src/index.i

# target to preprocess a source file
src/index.cpp.i:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/index.cpp.i
.PHONY : src/index.cpp.i

src/index.s: src/index.cpp.s

.PHONY : src/index.s

# target to generate assembly for a file
src/index.cpp.s:
	$(MAKE) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/index.cpp.s
.PHONY : src/index.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... app"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... src/Bullet.o"
	@echo "... src/Bullet.i"
	@echo "... src/Bullet.s"
	@echo "... src/CubicCurve.o"
	@echo "... src/CubicCurve.i"
	@echo "... src/CubicCurve.s"
	@echo "... src/Enemy.o"
	@echo "... src/Enemy.i"
	@echo "... src/Enemy.s"
	@echo "... src/EnemyBuilder.o"
	@echo "... src/EnemyBuilder.i"
	@echo "... src/EnemyBuilder.s"
	@echo "... src/EnemyFactory.o"
	@echo "... src/EnemyFactory.i"
	@echo "... src/EnemyFactory.s"
	@echo "... src/GameObject.o"
	@echo "... src/GameObject.i"
	@echo "... src/GameObject.s"
	@echo "... src/GameOverState.o"
	@echo "... src/GameOverState.i"
	@echo "... src/GameOverState.s"
	@echo "... src/GameState.o"
	@echo "... src/GameState.i"
	@echo "... src/GameState.s"
	@echo "... src/LevelDisplay.o"
	@echo "... src/LevelDisplay.i"
	@echo "... src/LevelDisplay.s"
	@echo "... src/LinearCurve.o"
	@echo "... src/LinearCurve.i"
	@echo "... src/LinearCurve.s"
	@echo "... src/MenuState.o"
	@echo "... src/MenuState.i"
	@echo "... src/MenuState.s"
	@echo "... src/Path.o"
	@echo "... src/Path.i"
	@echo "... src/Path.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/SlowGun.o"
	@echo "... src/SlowGun.i"
	@echo "... src/SlowGun.s"
	@echo "... src/SpawnElement.o"
	@echo "... src/SpawnElement.i"
	@echo "... src/SpawnElement.s"
	@echo "... src/Spawner.o"
	@echo "... src/Spawner.i"
	@echo "... src/Spawner.s"
	@echo "... src/StandardGun.o"
	@echo "... src/StandardGun.i"
	@echo "... src/StandardGun.s"
	@echo "... src/State.o"
	@echo "... src/State.i"
	@echo "... src/State.s"
	@echo "... src/StateManager.o"
	@echo "... src/StateManager.i"
	@echo "... src/StateManager.s"
	@echo "... src/TextureManager.o"
	@echo "... src/TextureManager.i"
	@echo "... src/TextureManager.s"
	@echo "... src/TriGun.o"
	@echo "... src/TriGun.i"
	@echo "... src/TriGun.s"
	@echo "... src/TriGunUpgrade.o"
	@echo "... src/TriGunUpgrade.i"
	@echo "... src/TriGunUpgrade.s"
	@echo "... src/Upgrade.o"
	@echo "... src/Upgrade.i"
	@echo "... src/Upgrade.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/index.o"
	@echo "... src/index.i"
	@echo "... src/index.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

